### ISSUE TITLE
When sending the request to Hetzner's API, an error occurred "Unprocessable Entity"

### ISSUE THREAD

**Issue by flying-sausages** [TimDaub/hetzner-cloud-deploy-server-action#12]
Not exactly sure what I'm doing wrong here, is there a possibility something changed on Hetzner's API? https://github.com/flying-sausages/swizzin/actions/runs/545383527

**Comment by TimDaub** [comment]
Hey @flying-sausages, thanks for reporting this issue.

I've looked at the provided link and can say that I think your inputs look syntactically correct.

The error is thrown here: https://github.com/TimDaub/hetzner-cloud-deploy-server-action/blob/main/lib.js#L75

> is there a possibility something changed on Hetzner's API?

Unlikely as it is versioned. Additionally, I'm using the GitHub Action on a daily basis for intergration tests, so I'm confident it wasn't broken.

Now to adress your issue:

- When trying to create a server, a 422 Unprocessable Entity starus is thrown. This means some of the values you'e provided in the action's inputs are incorrect.
- Are you sure your HToken is correct and that you've created it with write access? Have you stored it in the secrets of the Github Repo?
- Is your ssh key available and spelled correctly in the project that you also created a HToken for?

**Comment by flying-sausages** [comment]
Thanks for the quick response! Good to know it works for you, helps isolate this out. I copy pasted the example in now, made a secret with the same name copy-pasted from the code, and pasted in the multiline private key block there.

![image](https://user-images.githubusercontent.com/23618693/107149111-25ab8100-6957-11eb-979e-273436c399c4.png)

The keys and tokens exist on the Swizzin side, and they are tested and verified to work.

![image](https://user-images.githubusercontent.com/23618693/107149159-6905ef80-6957-11eb-8066-e03fe89bced9.png)

![image](https://user-images.githubusercontent.com/23618693/107149181-82a73700-6957-11eb-8cb4-d13cd5edddde.png)

**Comment by TimDaub** [comment]
👋🏼 

It looks good, though I'm confused why you need `HETZNER_SSH_KEY`.

- `secrets.SSH_PRIVATE_KEY` is supposed to contain your private key for the next action that is `webfactory/ssh-agent@v0.4.1` (so for the above-described issue, it won't influence the outcome of the request's status)
- `secrets.HCLOUD_TOKEN` is your Hetzner API key that has read and write capabilities. From the screenshot, it looks like you successfully created it
- `ssh-key-name` is the name of the ssh key that you uploaded to your Hetzner project. Telling from your screenshots it should be `ssh-key-name: "github"`.

**Comment by flying-sausages** [comment]
Looks like you're right, I did not realise that the `ssh-key-name` refers to the name of the key on Hetzner's side. Let's see if that fixed it.

**Comment by flying-sausages** [comment]
🎉 🎉 🎉 

Thanks for pointing this out!

![image](https://user-images.githubusercontent.com/23618693/107149383-98692c00-6958-11eb-8b85-c1e7b7931d93.png)

I'll see if I can modify the README.md a little so that this is more obvious the next time I blindly copy paste this ;)

**Comment by TimDaub** [comment]
Cool!

And yes, if you want to add a note about ssh-key-name in the Readme.md, I'd welcome and merge it!

**Comment by javidovl** [comment]
Hi,
I wondered where we should get the SSH key. Should it be from the server? I mean the one which we add to the SSH Keys section on Hetzner.

**Comment by TimDaub** [comment]
> Hi, I wondered where we should get the SSH key. Should it be from the server?

GitHub should have access to the SSH key that gives access to your server. It's because this action can allow you to log into your Hetzner server to run some scripts.

**Comment by javidovl** [comment]
Yeah, I believe you meant Deploy Keys. I added the ssh I got from the server to the Deploy Keys section in GitHub. But it says never used since I got errors. Should I also add this ssh key (the one I got from the server itself) to the Hetzner? It's kind of weird since I add the ssh key of the server to its provider website

**Comment by TimDaub** [comment]
> I added the ssh I got from the server to the Deploy Keys section in GitHub.

Deploy keys give authority to the key holder to GitHub Actions. If u want to control your Hetzner Server from GitHub Actions as is done e.g. here: https://github.com/TimDaub/hetzner-cloud-deploy-server-action#how-do-i-use-this-action-with-eg-a-domain-name you'll have to make the private key available to use from a GitHub Action and you'll have to put the public key as an authorized_key on your server. Makes sense?

**Comment by javidovl** [comment]
No, I believe I couldn't express myself clearly. My question is, where did you get the SSH key that you placed to Hetzner Cloud and write its name as `ssh-key-name`?

**Comment by TimDaub** [comment]
this key, you generate it in your host, then put it on Hetzner and select it upon servee creation
